version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8

  pre_build:
    commands:
      - echo Initializing environment
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain nw --domain-owner 120569621555 --region us-east-1 --query authorizationToken --output text)
      - echo Writing settings.xml with token
      - |
        cat > settings.xml <<EOF
        <settings>
          <servers>
            <server>
              <id>nw-nw-cicd</id>
              <username>aws</username>
              <password>$CODEARTIFACT_AUTH_TOKEN</password>
            </server>
          </servers>
          <profiles>
            <profile>
              <id>nw-nw-cicd</id>
              <activation>
                <activeByDefault>true</activeByDefault>
              </activation>
              <repositories>
                <repository>
                  <id>nw-nw-cicd</id>
                  <url>https://nw-120569621555.d.codeartifact.us-east-1.amazonaws.com/maven/nw-cicd/</url>
                </repository>
              </repositories>
            </profile>
          </profiles>
          <mirrors>
            <mirror>
              <id>nw-nw-cicd</id>
              <name>nw-nw-cicd</name>
              <url>https://nw-120569621555.d.codeartifact.us-east-1.amazonaws.com/maven/nw-cicd/</url>
              <mirrorOf>*</mirrorOf>
            </mirror>
          </mirrors>
        </settings>
        EOF

  build:
    commands:
      - echo Build started on `date`
      - mvn -s settings.xml compile

  post_build:
    commands:
      - echo Build completed on `date`
      - mvn -s settings.xml package

artifacts:
  files:
    - target/nextwork-web-project.war
  discard-paths: no
